### ISSUE TITLE
not run  delphi 7

### ISSUE THREAD

**Issue by xinjijia** [formeo/FirebirdRepairBase#2]
![image](https://cloud.githubusercontent.com/assets/17928411/26754605/48a1811c-48b0-11e7-82b6-8599965d71c9.png)
[Error] uDatabase.pas(135): Undeclared identifier: 'DDataPage'
[Fatal Error] main.pas(7): Could not compile used unit 'uDatabase.pas'

**Comment by xinjijia** [comment]
[Error] main.pas(426): Undeclared identifier: 'typeCutypePageChecksumrrPage'

**Comment by xinjijia** [comment]
Hello, this program is not working, and can he support firebird 3.0?

**Comment by formeo** [comment]
Hello, I'm working at the moment on fix and refactoring. I'll try to fix this error.

**Comment by formeo** [comment]
This program wil not support firebird 3, in next commits at least, but i will be develop in this direction

**Comment by formeo** [comment]
You can use IBSurgeon FirstAID 5.0 http://ib-aid.com/en/ibsurgeon-firstaid/,
I applied it and could pump some data from my crashed DB, However it is not free.

**Comment by xinjijia** [comment]
OK thanks
